---
title: "stat3355_data_cleaning"
output: pdf_document
date: "2025-10-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data_cleaning

```{r platforms}
library(dplyr)
netflix <- read.csv("netflix_titles.csv")
hulu <- read.csv("hulu_titles.csv")
amazon <- read.csv("amazon_prime_titles.csv")
disney <- read.csv("disney_plus_titles.csv")

netflix$platform <- "Netflix"
hulu$platform <- "Hulu"
amazon$platform <- "Amazon Prime"
disney$platform <- "Disney+"

#combining all datasets in one table
all_data <- bind_rows(netflix, hulu, amazon, disney)

# changing UR and NR to unrated/ NA to unknown
all_data$rating <- toupper(all_data$rating)
all_data$rating <- trimws(all_data$rating)
all_data$rating[all_data$rating %in% c("UR", "NR", "UNRATED", "NOT RATED", "NOT_RATE", "UNKNOWN", "TV-NR")] <- "Unrated"
all_data$rating <- gsub("AGES_18_|18\\+", "R", all_data$rating)
all_data$rating <- gsub("AGES_16_|16\\+", "TV-14", all_data$rating)
all_data$rating <- gsub("13\\+", "PG-13", all_data$rating)
all_data$rating <- gsub("ALL|ALL_AGES", "G", all_data$rating)
all_data$rating[is.na(all_data$rating)] <- "Unknown"
all_data$rating <- gsub("^16$", "TV-14", all_data$rating)
all_data$rating <- gsub("^7\\+$", "TV-Y7", all_data$rating)
unique(all_data$rating)
##all_data$rating[all_data$rating == ""] <- "Unknown"

all_data$rating[grepl("MIN|SEASON", all_data$rating)] <- NA
table(all_data$rating)
# cleaning duration

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
